package scaffold

import (
	"fmt"
	"github.com/spf13/cobra"
)

func NewCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "scaffold [flags]",
		Short: "Generates necessary files required for module creation",
		Long: `This is a long description of how the files necessary for module creation are generated by the magic of
this scaffold command. Magic is great, magic is magical.`,
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Println("This is the help message of the `scaffold` command")
		},
	}

	return cmd
}
